// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBppdZ-cX8jBO21f1mrCpN7BCRdsox-dTE',
    appId: '1:388737115031:web:9506de7c62b0edc4a31ad2',
    messagingSenderId: '388737115031',
    projectId: 'realecommerce-fb194',
    authDomain: 'realecommerce-fb194.firebaseapp.com',
    storageBucket: 'realecommerce-fb194.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVtOfknJdKVTfafY-cbK6GkUuEwtiYKc',
    appId: '1:388737115031:android:db2a8a9e08e37db0a31ad2',
    messagingSenderId: '388737115031',
    projectId: 'realecommerce-fb194',
    storageBucket: 'realecommerce-fb194.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc5VUW_ydo2OkbrqyOTC7PWAlrUuStPwE',
    appId: '1:388737115031:ios:4d2fea3720029d42a31ad2',
    messagingSenderId: '388737115031',
    projectId: 'realecommerce-fb194',
    storageBucket: 'realecommerce-fb194.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc5VUW_ydo2OkbrqyOTC7PWAlrUuStPwE',
    appId: '1:388737115031:ios:4d2fea3720029d42a31ad2',
    messagingSenderId: '388737115031',
    projectId: 'realecommerce-fb194',
    storageBucket: 'realecommerce-fb194.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBppdZ-cX8jBO21f1mrCpN7BCRdsox-dTE',
    appId: '1:388737115031:web:7376807fb87b9ed1a31ad2',
    messagingSenderId: '388737115031',
    projectId: 'realecommerce-fb194',
    authDomain: 'realecommerce-fb194.firebaseapp.com',
    storageBucket: 'realecommerce-fb194.firebasestorage.app',
  );
}
